# Generated by Django 4.2.4 on 2023-08-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodmapStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=250)),
                ('restaurantname', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('contactinfo', models.CharField(max_length=250)),
                ('googlelink', models.TextField()),
                ('openingtime', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('ratingintotaloffive', models.FloatField()),
            ],
        ),
    ]
