# Generated by Django 4.2.4 on 2023-08-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingMaptemplate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmapstore',
            name='ratingcategories',
            field=models.CharField(blank=True, choices=[('兩分', '兩分'), ('四分或以上', '四分或以上'), ('三分', '三分'), ('兩分或以下', '兩分或以下')], max_length=30, null=True),
        ),
    ]
